apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: docker-registry-jx.k8s0.dukecon.org
  environments:
  - key: dev
    owner: ascheman
    repository: jx3-microk8s-demo-2021-01-15
  - key: staging
  - key: production
  ingress:
    domain: k8s0.dukecon.org
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: ascheman
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
