apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        ascheman/jx3-demo-golang-http-2021-01-16: true
        ascheman/jx3-microk8s-demo-2021-01-15: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        ascheman/jx3-demo-golang-http-2021-01-16: merge
        ascheman/jx3-microk8s-demo-2021-01-15: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - ascheman/jx3-microk8s-demo-2021-01-15
        - ascheman/jx3-demo-golang-http-2021-01-16
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - ascheman/jx3-microk8s-demo-2021-01-15
        - ascheman/jx3-demo-golang-http-2021-01-16
      target_url: http://dashboard-jx.k8s0.dukecon.org
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
