apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - ascheman/jx3-microk8s-demo-2021-01-15
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - ascheman/jx3-demo-golang-http-2021-01-16
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - ascheman/jx3-demo-spring-boot-2021-01-18
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      ascheman/jx3-demo-golang-http-2021-01-16:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      ascheman/jx3-demo-spring-boot-2021-01-18:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      ascheman/jx3-microk8s-demo-2021-01-15:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - ascheman/jx3-microk8s-demo-2021-01-15
      trusted_org: todo
    - repos:
      - ascheman/jx3-demo-golang-http-2021-01-16
      trusted_org: todo
    - repos:
      - ascheman/jx3-demo-spring-boot-2021-01-18
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
