apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ascheman
    provider: github
    repository: jx3-demo-golang-http-2021-01-16
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: ascheman-jx3-demo-golang-http-2021-01-16
  namespace: jx
spec:
  httpCloneURL: https://github.com/ascheman/jx3-demo-golang-http-2021-01-16.git
  org: ascheman
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx3-demo-golang-http-2021-01-16
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/ascheman/jx3-demo-golang-http-2021-01-16
