# Source: jx3-demo-golang-http-2021-01-16/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-18T15:04:00Z"
  deletionTimestamp: null
  name: 'jx3-demo-golang-http-2021-01-16-0.0.4'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.4
      sha: 6f9aedb0b6d2646577e89a5c8a172e7da3638f8a
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 36aed5e8bb82926dca49c3f6a3b1ffdfacfa67c4
  gitHttpUrl: https://github.com/ascheman/jx3-demo-golang-http-2021-01-16
  gitOwner: ascheman
  gitRepository: jx3-demo-golang-http-2021-01-16
  name: 'jx3-demo-golang-http-2021-01-16'
  releaseNotesURL: https://github.com/ascheman/jx3-demo-golang-http-2021-01-16/releases/tag/v0.0.4
  version: v0.0.4
status: {}
